version: "3.5"

services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
          - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=mongodb.2022
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=mongodb.2022
            - ME_CONFIG_MONGODB_SERVER=mongodb
        ports:
            - 83:8081

networks:
    default:
        name: mongodb_network
