version: '3.5'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    hostname: mariadb_host
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb.2022
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
